### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by mahaoming2022** [CmdBlockZQG/oi-runner#1]
绝对还不错,但是怎么编译没搞懂.

没用运行语言框呀?

**Comment by CmdBlockZQG** [comment]
我没能明白你的意思 能详细说说您遇到的问题吗？

**Comment by mahaoming2022** [comment]
已经解决了.thx

非常好用,直接把微软的C++卸载了

**Comment by mahaoming2022** [comment]
已经解决了,很好用,支持,已经点了star了.

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年5月3日 23:39
收件人: ***@***.***>
抄送: ***@***.***>; State ***@***.***>
主题: Re: [CmdBlockZQG/oi-runner] 问题 (Issue #1)


我没能明白你的意思 能详细说说您遇到的问题吗？

―
