### ISSUE TITLE
Linux使用时遇到错误

### ISSUE THREAD

**Issue by catmeowjiao** [CmdBlockZQG/oi-runner#3]
我在编译运行`abcd.cpp`时,提示:
Error: spawn abcd ENOENT
exit with code -2 in 0.001s

**Comment by CmdBlockZQG** [comment]
如果是编译期间出的问题 检查你是否安装了gcc编译器
如果是运行期间出的问题 可能是你的配置文件写的有问题
可以看看你的配置文件吗

**Comment by catmeowjiao** [comment]
我的vscode已经卸载了（（（
